### ISSUE TITLE
6th bar support

### ISSUE THREAD

**Issue by Leiludallas** [L3n1n/NeavUI-Classic#1]
With my hunter, a total of 5 bars is not enough compare to BFA. Maybe a 6th would be great. With a mouseover functionality would be godlike. Thank you.

**Comment by L3n1n** [comment]
Like that?

![](https://i.imgur.com/FwYCfeg.jpg)

**Comment by Leiludallas** [comment]
Great

**Comment by L3n1n** [comment]
I think it will be work good now. Please test a few days and report me about result. Thanks.
