### ISSUE TITLE
Pet bar position

### ISSUE THREAD

**Issue by Leiludallas** [L3n1n/NeavUI-Classic#2]
Hi,

The pet bar is right in the middle of the screen.
![2019-09-04 22_16_24-World of Warcraft](https://user-images.githubusercontent.com/39462014/64288237-e1e26a00-cf61-11e9-9b5d-7e5b2c10dc8a.png)

**Comment by L3n1n** [comment]
Press Shift + Alt and drag with your left mouse button on the first button of pet's bar to move.

**Comment by Leiludallas** [comment]
Ty
