### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Schanzation** [L3n1n/NeavUI-Classic#3]
Hi! Not sure where to ask questions about the mod. Is it here?

Anywhoo, I was wondering a few things.

1. I don't want class colored minimap, but I want about the same border as the nBuffs. How would one do that?

2. How to remove the night/day circle on the minimap?

3. How to remove the 'Chat Channels' icon in the chat?

4. In the chat. How could I make it say [GEN] or [TRADE] instead of (1) or (2)

5. nPower. How does one remove the arrows pointing at your current energy? Also would love to see an option to display the HP also =)

**Comment by L3n1n** [comment]
Hello! Yes you can ask me here. It's okay but you need to know i'm not a developer of that UI.

1. I updated nMinamap and now you can disable class color for border in config.lua
2. I already did thay, you need to update nMinamap.
3. In nChat/config.lua set param enableVoiceChatButtons to false
4. You need to modify nChat/core.php: find function FCF_AddMessage and remove condition "if end" and everything in between.
5. You need to modify nPower/core.php: find function UpdateBar and remove UpdateArrow()

**Comment by Schanzation** [comment]
I will try that now. Thanks so much!

**Comment by Schanzation** [comment]
I love copy chat function when I use BasicChatMods, but it's not working for me in nChat.

**Comment by L3n1n** [comment]
nChat has own copy chat function.

**Comment by Schanzation** [comment]
Yes I know. It's not working.

**Comment by L3n1n** [comment]
I tested nChat and it works well. When you see link in chat it has a different color and you can click that, after that your chatbox will have a link text which you can copy.
